<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="" total="4" errors="0" failures="1" not-run="1" inconclusive="1" ignored="1" skipped="0" invalid="0" date="2017-11-08" time="15:04:58">
  <environment nunit-version="1.0.0.0" clr-version="4.0.50524.0" os-version="Unix 3.10.0.0" platform="Unix" cwd="/" machine-name="localhost" user="somebody" user-domain="localhost" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="TestSuite" name="" executed="True" result="Failure" success="False" time="0.662" asserts="2">
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
      <stack-trace />
    </failure>
    <results>
      <test-suite type="Assembly" name="/UnitTestApp1.dll" executed="True" result="Failure" success="False" time="0.606" asserts="2">
        <properties>
          <property name="_PID" value="2568" />
          <property name="_APPDOMAIN" value="RootDomain" />
        </properties>
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
          <stack-trace />
        </failure>
        <results>
          <test-suite type="TestFixture" name="TestsSample" executed="True" result="Failure" success="False" time="0.591" asserts="2">
            <failure>
              <message><![CDATA[One or more child tests had errors]]></message>
              <stack-trace />
            </failure>
            <results>
              <test-case name="This_Test_Will_Be_Ignored / Debug" executed="False" result="Ignored">
                <properties>
                  <property name="_SKIPREASON" value="another time" />
                </properties>
                <reason>
                  <message><![CDATA[another time]]></message>
                </reason>
              </test-case>
              <test-case name="This_Test_Will_Be_Inconclusive / Debug" executed="True" result="Inconclusive" success="False" time="0.245" asserts="0" />
              <test-case name="This_Test_Will_Fail / Debug" executed="True" result="Failure" success="False" time="0.073" asserts="1">
                <failure>
                  <message><![CDATA[  Expected: False
  But was:  True
]]></message>
                  <stack-trace><![CDATA[  at UnitTestApp1.TestsSample.This_Test_Will_Fail () [0x00001] in <21b791be2b8b428dbdac8baf8f0134f5>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <7771c78b64d7486dacaffa197e02a1ea>:0 
]]></stack-trace>
                </failure>
              </test-case>
              <test-case name="This_Test_Will_Pass / Debug" executed="True" result="Success" success="True" time="0.046" asserts="1" />
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>